
[project]
name = "psy"
version = "0.1.0"
requires-python = ">=3.10"
description = "PSyclone xDSL transformations"
authors = [
    { name = "Nick Brown" },
    { name = "Maurice Jamieson" },
]
readme = "README.md"
license = { text = "BSD-3-Clause" }
keywords = ["gpu", "stencil", "compiler"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent"
]

dependencies = [ "xdsl<0.36", "psyclone@git+https://github.com/xdslproject/PSyclone.git@xdsl_backend"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[project.scripts]
psy-opt = "psy.tools.psy_opt:main"
